### ISSUE TITLE
Mass patrol isn't working

### ISSUE THREAD

**Issue by Sinfadiel** [wikimedia/mediawiki-gadgets-RTRC#117]
Hi,

French Wiktionary patrol rely on RTRC, and we usually succeed to review every recent changes. Sadly, Mass patrol isn't working anymore for about a month. It is unclear why, but it just mark one edit and do not follow on. It was very used to clear a lot of edit by a new editors that got it right but was too fresh. Our main patroller is about to quit for this reason, so if you have some fix, it will be greatly appreciated!

Anyway, thanks a lot for this tool!

**Comment by Krinkle** [comment]
Mass patrol works for me on <https://test.wikipedia.org>.

Last month there was a regression in MediaWiki, which caused RTRC to be unable to find the patrol link. This was reported at https://github.com/Krinkle/mw-gadget-rtrc/issues/115, but solved in Phabricator at https://phabricator.wikimedia.org/T357693. No changes in RTRC caused or fixed the issue.

In the last two weeks, I believe it has been working again. Can you confirm this? What happens when you try to use Mass Patrol? Can you show a screenshot?

**Comment by Sinfadiel** [comment]
Well, it stopped around the 14th of February, sounds right. I saw the phab ticket, but I am not convince it is relate. In French Wiktionary, a lot of people use Timeless. Anyway, I am using Vector 2020. I will investigate for eventual problems related to the skin. 

When I start a Mass patrol, lines switches to green but their status is not changed, they stay marked.  
![image](https://github.com/Krinkle/mw-gadget-rtrc/assets/60888373/1664ab4a-6e99-4778-bca0-e86ff78697fd)

In French Wiktionary, Patroller is a status obtained by an election but if you need, we can skip the procedure and give you the user rights in order to test by yourself on this specific project.

**Comment by Krinkle** [comment]
Thanks. I've exported the issue tracker to Phabricator. This issue continues at <https://phabricator.wikimedia.org/T361304>. Subscribe there for updates!
